



------------------------------------ BANK_CUSTOMER_CHURN --------------------------------


CREATE DATABASE BANK_CUSTOMER_CHURN

USE BANK_CUSTOMER_CHURN

---------- IMPORTING DATA (JUST ONE TABLE)

	SELECT * FROM BANK_CHURN 

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BANK_CHURN'


	--  BALANCE FIELD DATATYPE CHANGE
	SELECT BALANCE, CAST(BALANCE AS FLOAT) AS NEW
	FROM BANK_CHURN 

	UPDATE BANK_CHURN SET BALANCE = CAST(BALANCE AS FLOAT)

	ALTER TABLE BANK_CHURN ALTER COLUMN BALANCE FLOAT

	--  ESTIMATED_SALARY FIELD DATATYPE CHANGE
	SELECT ESTIMATED_SALARY, CAST(ESTIMATED_SALARY AS FLOAT) AS NEW
	FROM BANK_CHURN 

	UPDATE BANK_CHURN SET ESTIMATED_SALARY = CAST(ESTIMATED_SALARY AS FLOAT)

	ALTER TABLE BANK_CHURN ALTER COLUMN ESTIMATED_SALARY FLOAT





	-- CHECKING DUPLICATES (NONE FOUND)

	SELECT * 
	FROM ( SELECT *, ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY (SELECT NULL)) AS RN
			FROM BANK_CHURN) T
	WHERE RN >1 



	SELECT * FROM BANK_CHURN 

	SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BANK_CHURN'






	-- CHANGING COLUMN_NAMES

	EXEC SP_RENAME 'BANK_CHURN.HAS_CC_YES_NO', 'Has_CC_Yes_No', 'COLUMN'







	-- CHECKING MISSING/BLANK VALUES (NONE FOUND)

	SELECT SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN SURNAME = ' ' THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN CREDIT_SCORE IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN [GEOGRAPHY] = ' ' THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN GENDER = ' ' THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN AGE IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN TENURE IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN BALANCE IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN NUM_OF_PRODUCTS IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN HAS_CREDIT_CARD IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN HAS_CC_YES_NO = ' ' THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN IS_ACTIVE_MEMBER IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN ESTIMATED_SALARY IS NULL THEN 1 ELSE 0 END) AS CUST_ID,
			SUM(CASE WHEN EXITED IS NULL THEN 1 ELSE 0 END) AS CUST_ID
		FROM BANK_CHURN

























