


------------------------- BANK_CHURN SQL ANALYSIS -------------------

USE BANK_CUSTOMER_CHURN

SELECT * FROM BANK_CHURN

SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BANK_CHURN'

SELECT UPPER( ' What types of segments exist within the banks customers? ' )

	ALTER TABLE BANK_CHURN ADD CHURN VARCHAR(50)

	UPDATE BANK_CHURN SET CHURN = 'Churner' 
	WHERE CHURN = 'CHURNER'

	UPDATE BANK_CHURN SET CHURN = 'Non Chruner' 
	WHERE CHURN = 'NON CHURNER'

-- 1.  WHAT ATTRIBUTES ARE MORE COMMON AMONG CHURNERS THAN NON-CHURNERS? CAN CHURN BE PREDICTED USING THE VARIABLES IN THE DATA? 
	
	-- A. COUNT AND PERCENTAGE OF CHURNERS VS NON-CHURNERS (20.37% CHURNERS)

	WITH CTE1 AS 
	(SELECT CHURN, COUNT(CUSTOMER_ID) AS CNT
	FROM BANK_CHURN
	GROUP BY CHURN),
	
	SUM_CTE AS 
	(SELECT * , 
		SUM(CNT) OVER () AS TOTAL_CNT
	FROM CTE1)
	
	SELECT CHURN, CNT, 
		CAST(ROUND(CNT*100.0/TOTAL_CNT,3) AS DECIMAL(4,2)) AS PRECENT_TOT
	FROM SUM_CTE 


	-- B. AVERAGE CREDIT_SCORE VS CHURN
			-- CHURNERS HAVE SLIGHTLY LOW CS

	SELECT * FROM BANK_CHURN

	SELECT CHURN, ROUND(AVG(CREDIT_SCORE),2) AS AVG_CREDIT_SCORE
	FROM BANK_CHURN
	GROUP BY CHURN

	-- C. CHRUN VS GEOGRAPHY (GERMANY AND FRANCE WITH HIGHEST CHURNERS)

	SELECT CHURN, [GEOGRAPHY], COUNT(CUSTOMER_ID) AS CNT
	FROM BANK_CHURN
	WHERE CHURN = 'CHURNER'
	GROUP BY CHURN, [GEOGRAPHY]
	ORDER BY CNT DESC

	-- D. CHRUN VS GENDER (MORE FEMALE CHURNERS)

	SELECT CHURN, GENDER, COUNT(CUSTOMER_ID) AS CNT
	FROM BANK_CHURN
	WHERE CHURN = 'CHURNER'
	GROUP BY CHURN, GENDER
	ORDER BY CNT DESC

	-- E. CHURN VS AGE

	SELECT * FROM BANK_CHURN

	SELECT CHURN, AVG(AGE) AS AVG_AGE
	FROM BANK_CHURN
	GROUP BY CHURN

	-- F. CHURN VS TENURE

	SELECT * FROM BANK_CHURN

	SELECT CHURN, AVG(TENURE) AS AVG_TENURE
	FROM BANK_CHURN
	GROUP BY CHURN

	-- G. CHURN VS AVG BALANCE AND ESTIMATED_SALARY (CHURNERS HAVE HIGHER BALANCE)

	SELECT * FROM BANK_CHURN

	SELECT CHURN, AVG(BALANCE) AS AVG_BALANCE
	FROM BANK_CHURN
	GROUP BY CHURN

	SELECT CHURN, AVG(ESTIMATED_SALARY) AS AVG_ESTIMATED_SALARY
	FROM BANK_CHURN
	GROUP BY CHURN

	-- H. CHURN VS NUM_OF_PRODUCTS

	SELECT CHURN, NUM_OF_PRODUCTS, COUNT(CUSTOMER_ID) AS CUST_CNT
	FROM BANK_CHURN
	GROUP BY CHURN, NUM_OF_PRODUCTS
	ORDER BY CHURN

	-- I. CHURN VS HAS_CREDIT_CARD

	SELECT * FROM BANK_CHURN

	SELECT CHURN, HAS_CREDIT_CARD, COUNT(CUSTOMER_ID) AS CUST_CNT
	FROM BANK_CHURN
	GROUP BY CHURN, HAS_CREDIT_CARD
	ORDER BY CHURN

	-- I. CHURN VS IS_ACTIVE_MEMBER

	SELECT * FROM BANK_CHURN

	SELECT CHURN, IS_ACTIVE_MEMBER, COUNT(CUSTOMER_ID) AS CUST_CNT
	FROM BANK_CHURN
	GROUP BY CHURN, IS_ACTIVE_MEMBER
	ORDER BY CHURN


-- 2.  WHAT DO THE OVERALL DEMOGRAPHICS OF THE BANK'S CUSTOMERS LOOK LIKE? 
	
	SELECT * FROM BANK_CHURN

	SELECT GENDER, [GEOGRAPHY], AVG(AGE) AS AVG_AGE, AVG(TENURE) AS AVG_TENURE
	FROM BANK_CHURN
	GROUP BY GENDER, [GEOGRAPHY]
	ORDER BY [GEOGRAPHY]


-- 3.  IS THERE A DIFFERENCE BETWEEN GERMAN, FRENCH, AND SPANISH CUSTOMERS IN TERMS OF ACCOUNT BEHAVIOR? 

-- 4.  WHAT TYPES OF SEGMENTS EXIST WITHIN THE BANK'S CUSTOMERS? 
		-- AVG CREDIT SCORE
		-- GENDER
		-- AVG_AGE / AGE GROUP
		-- HAS CREDIT CARD
		-- CHURN
